defaultTheme = {
    "title": "My Personal Bests",
    "panelTitleHeight": "100",
    "panelTitleTextShadow": false,
    "panelTitleBackgroundType": "image",
    "panelTitleFontBold": false,
    "panelTitleFontItalic": false,
    "panelTitleFontSize": "30",
    "panelTitleFontColor": "#ffffff",
    "panelTitleFontFamily": "Roboto Condensed",
    "panelTitleShadow": false,
    "categoryHeaderFontBold": false,
    "categoryHeaderFontItalic": false,
    "categoryHeaderFontSize": "14",
    "categoryHeaderFontColor": "#ffffff",
    "categoryHeaderFontFamily": "Roboto Condensed",
    "pbHeaderFontBold": false,
    "pbHeaderFontItalic": false,
    "pbHeaderFontSize": "14",
    "pbHeaderFontColor": "#ffffff",
    "pbHeaderFontFamily": "Roboto Condensed",
    "wrHeaderFontBold": false,
    "wrHeaderFontItalic": false,
    "wrHeaderFontSize": "14",
    "wrHeaderFontColor": "#ffffff",
    "wrHeaderFontFamily": "Roboto Condensed",
    "hideWR": false,
    "wrRainbow": false,
    "panelTitleDivHeight": "5",
    "panelTitleDivColor": "#008000",
    "panelTitleDivBottomMargin": "0",
    "gameTitleFontBold": false,
    "gameTitleFontItalic": false,
    "gameTitleFontSize": "19",
    "gameTitleFontColor": "#ffffff",
    "gameTitleFontFamily": "Roboto Condensed",
    "expandContractColor": "#ffffff",
    "gameCategoryFontBold": false,
    "gameCategoryFontItalic": false,
    "gameCategoryFontSize": "14",
    "gameCategoryFontColor": "#f1eecb",
    "gameCategoryFontFamily": "Roboto Condensed",
    "gameCategoryBottomMargin": "0",
    "pbFontBold": false,
    "pbFontItalic": false,
    "pbFontSize": "15",
    "pbFontColor": "#ffffff",
    "pbFontFamily": "Roboto Condensed",
    "wrFontBold": false,
    "wrFontItalic": false,
    "wrFontSize": "15",
    "wrFontColor": "#f3e221",
    "wrFontFamily": "Roboto Condensed",
    "miscHeaderFontBold": false,
    "miscHeaderFontItalic": false,
    "miscHeaderFontSize": "15",
    "miscHeaderFontColor": "#ffffff",
    "miscHeaderFontFamily": "Roboto Condensed",
    "miscHeaderBottomMargin": "0",
    "miscShow": true,
    "miscSep": true,
    "ilHeaderFontBold": false,
    "ilHeaderFontItalic": false,
    "ilHeaderFontSize": "15",
    "ilHeaderFontColor": "#ffffff",
    "ilHeaderFontFamily": "Roboto Condensed",
    "ilHeaderBottomMargin": "0",
    "ilShow": true,
    "ilSep": true,
    "gameDivHeight": "5",
    "gameDivColor": "#205f6b",
    "gameDivBottomMargin": "5",
    "panelBackgroundColor": "#101010",
    "scrollbarWidth": "5",
    "scrollbarOpacity": "100",
    "scrollbarColor": "#424242"
}
