defaultTheme = {
    "title":"A very very very very very long title",
    "panelTitleDivColor":"#008000",
    "gameTitleDivColor":"#205f6b",
    "panelBackgroundColor":"#101010",
    "wrRainbow":false,
    "hideWR":false,
    "miscShow":true,
    "miscSep":false,
    "ilShow":true,
    "ilSep":false,
    "panelTitleShadow":false,
    "panelTitleHeight":"100",
    "panelTitleBackgroundType":"image",
    "panelTitleFontBold":false,
    "panelTitleFontItalic":false,
    "panelTitleFontSize":"30",
    "panelTitleFontColor":"#ffffff",
    "panelTitleFont":"'Roboto Condensed', sans-serif",
    "panelHeaderFontBold":false,
    "panelHeaderFontItalic":false,
    "panelHeaderFontSize":"15",
    "panelHeaderFontColor":"#ffffff",
    "panelHeaderFont":"'Roboto Condensed', sans-serif",
    "gameTitleFontBold":false,"gameTitleFontItalic":false,
    "gameTitleFontSize":"19","gameTitleFontColor":"#ffffff",
    "gameTitleFont":"'Roboto Condensed', sans-serif",
    "gameCategoryFontBold":false,
    "gameCategoryFontItalic":false,
    "gameCategoryFontSize":"14",
    "gameCategoryFontColor":"#f1eecb",
    "gameCategoryFont":"'Roboto Condensed', sans-serif",
    "pbFontBold":false,
    "pbFontItalic":false,
    "pbFontSize":"15",
    "pbFontColor":"#ffffff",
    "pbFont":"'Roboto Condensed', sans-serif",
    "timeHeaderFontBold":false,
    "timeHeaderFontItalic":false,
    "timeHeaderFontSize":"15",
    "timeHeaderFontColor":"#ffffff",
    "timeHeaderFont":"'Roboto Condensed', sans-serif"
}